cides_homepage:
    path:     /
    defaults: { _controller: CidesBundle:Default:index }
cides_homepage_index:
    path:     /user/
    defaults: { _controller: CidesBundle:User:index }
cides_homepage_add:
    path:     /user/add
    defaults: { _controller: CidesBundle:User:add }
cides_homepage_edit:
    path:     /user/edit/{id}
    defaults: { _controller: CidesBundle:User:edit }
cides_homepage_view:
    path:     /user/view/{id}
    defaults: { _controller: CidesBundle:User:view }
cides_homepage_delete:
    path:     /user/delete/{id}
    defaults: { _controller: CidesBundle:User:delete }
