cides_homepage_index:
    path:     /user/index
    defaults: { _controller: CidesBundle:User:index }
cides_homepage_add:
    path:     /user/add
    defaults: { _controller: CidesBundle:User:add }
cides_homepage_create:
    path:     /user/create
    defaults: { _controller: CidesBundle:User:create }
    methods:  POST
cides_homepage_edit:
    path:     /user/edit/{id}
    defaults: { _controller: CidesBundle:User:edit }
cides_homepage_view:
    path:     /user/view/{id}
    defaults: { _controller: CidesBundle:User:view }
cides_homepage_delete:
    path:     /user/delete/{id}
    defaults: { _controller: CidesBundle:User:delete }
# Autentication

cides_homepage:
    path:     /
    defaults: { _controller: CidesBundle:User:home }

cides_login:
    path:     /login
    defaults: { _controller: CidesBundle:Security:login }

cides_login_check:
    path:     /login_check
    defaults: { _controller: CidesBundle:Security:loginCheck }

cides_logout:
    path:     /logout
